export const ADD_TODOLIST_REQUEST = "ADD_TODOLIST_REQUEST";
export const ADD_TODOLIST_SUCCESS = "ADD_TODOLIST_SUCCESS";
export const ADD_TODOLIST_FAILURE = "ADD_TODOLIST_FAILURE";

export const DELETE_TODOLIST_REQUEST = "DELETE_TODOLIST_REQUEST";
export const DELETE_TODOLIST_SUCCESS = "DELETE_TODOLIST_SUCCESS";
export const DELETE_TODOLIST_FAILURE = "DELETE_TODOLIST_FAILURE";

export const UPDATE_TODOLIST_REQUEST = "UPDATE_TODOLIST_REQUEST";
export const UPDATE_TODOLIST_SUCCESS = "UPDATE_TODOLIST_SUCCESS";
export const UPDATE_TODOLIST_FAILURE = "UPDATE_TODOLIST_FAILURE";

export const PAGINATION_SEARCH_SORT_TODOLIST_REQUEST =
  "PAGINATION_SEARCH_SORT_TODOLIST_REQUEST";
export const PAGINATION_SEARCH_SORT_TODOLIST_SUCCESS =
  "PAGINATION_SEARCH_SORT_TODOLIST_SUCCESS";
export const PAGINATION_SEARCH_SORT_TODOLIST_FAILURE =
  "PAGINATION_SEARCH_SORT_TODOLIST_FAILURE";

export const ADD_STATUS_REQUEST = "ADD_STATUS_REQUEST";
export const ADD_STATUS_SUCCESS = "ADD_STATUS_SUCCESS";
export const ADD_STATUS_FAILURE = "ADD_STATUS_FAILURE";
export const GET_STATUS_REQUEST = "GET_STATUS_REQUEST";
export const GET_STATUS_SUCCESS = "GET_STATUS_SUCCESS";
export const GET_STATUS_FAILURE = "GET_STATUS_FAILURE";

export const DELETE_STATUS_REQUEST = "DELETE_STATUS_REQUEST";
export const DELETE_STATUS_SUCCESS = "DELETE_STATUS_SUCCESS";
export const DELETE_STATUS_FAILURE = "DELETE_STATUS_FAILURE";

export const UPDATE_STATUS_REQUEST = "UPDATE_STATUS_REQUEST";
export const UPDATE_STATUS_SUCCESS = "UPDATE_STATUS_SUCCESS";
export const UPDATE_STATUS_FAILURE = "UPDATE_STATUS_FAILURE";

export const PAGINATION_SEARCH_SORT_STATUS_REQUEST =
  "PAGINATION_SEARCH_SORT_STATUS_REQUEST";
export const PAGINATION_SEARCH_SORT_STATUS_SUCCESS =
  "PAGINATION_SEARCH_SORT_STATUS_SUCCESS";
export const PAGINATION_SEARCH_SORT_STATUS_FAILURE =
  "PAGINATION_SEARCH_SORT_STATUS_FAILURE";

export const ADD_DETAIL_REQUEST = "ADD_DETAIL_REQUEST";
export const ADD_DETAIL_SUCCESS = "ADD_DETAIL_SUCCESS";
export const ADD_DETAIL_FAILURE = "ADD_DETAIL_FAILURE";

export const DELETE_DETAIL_REQUEST = "DELETE_DETAIL_REQUEST";
export const DELETE_DETAIL_SUCCESS = "DELETE_DETAIL_SUCCESS";
export const DELETE_DETAIL_FAILURE = "DELETE_DETAIL_FAILURE";

export const UPDATE_DETAIL_REQUEST = "UPDATE_DETAIL_REQUEST";
export const UPDATE_DETAIL_SUCCESS = "UPDATE_DETAIL_SUCCESS";
export const UPDATE_DETAIL_FAILURE = "UPDATE_DETAIL_FAILURE";

export const PAGINATION_SEARCH_SORT_DETAIL_REQUEST =
  "PAGINATION_SEARCH_SORT_DETAIL_REQUEST";
export const PAGINATION_SEARCH_SORT_DETAIL_SUCCESS =
  "PAGINATION_SEARCH_SORT_DETAIL_SUCCESS";
export const PAGINATION_SEARCH_SORT_DETAIL_FAILURE =
  "PAGINATION_SEARCH_SORT_DETAIL_FAILURE";

export const LIMIT = 5;

export const Isremote = {
  IsCreate: "IsCreate",
  IsUpdate: "IsUpdate",
  IsDelete: "IsDelete",
};
